name: CompatNoCheatPlus
main: me.asofold.bpl.cncp.CompatNoCheatPlus
version: ${project.version}-s${BUILD_SERIES}-b${BUILD_NUMBER}
dev-url: http://dev.bukkit.org/server-mods/compatnocheatplus-cncp/

loadbefore:
- NoCheatPlus
softdepend:
- mcMMO
- Citizens
- MagicSpells

commands:
  compatnocheatplus:
    description: 'Show general version information of cncp and dependencies.'
    usage: '/<command>'
    permission: 'cncp.cmd.info'
    aliases:
    - cncp
